name: WPCS
on:
  push:
    branches:
      - development
jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            enable_warnings: true
            paths: 'init.php mappings.php settings.php'
            standard: 'WordPress-Core'